POST /auth/register
Host: localhost:8080
Content-Type: application/json

{
  "email": "yusuf2@mail.com",
  "password": "1111",
  "confirm_password": "1111"
}
###

POST /auth/login
Host: localhost:8080
Content-Type: application/json

{
  "email": "yusuf2@mail.com",
  "password": "1111"
}
###

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksInJvbGUiOiJ1c2VyIiwiZW1haWwiOiJ5dXN1ZjJAbWFpbC5jb20iLCJpYXQiOjE3NTMwMzAyODksImV4cCI6MTc1MzAzNzQ4OX0.fgEg95KoCs_tETNkZAllKUgbXrr-4fJGl7OFYM7zevU
###
