POST /auth/register
Host: localhost:8080
Content-Type: application/json

{
  "email": "yusuf2@mail.com",
  "password": "1111",
  "confirm_password": "1111"
}
###

POST /auth/login
Host: localhost:8080
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "admin123"
}
###

GET /users/profile HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImVtYWlsIjoieXVzdWYyQG1haWwuY29tIiwiaWF0IjoxNzUzMDMyNTgzLCJleHAiOjE3NTMwMzk3ODN9.rFT2zQ94UgO6YkVmcfkAOas7JC0VLxum89ZTYgOBKbw

###


PATCH /users/profile HTTP/1.1
Host: localhost:8080
Content-Type: multipart/form-data; boundary=----WebkitBoundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksImVtYWlsIjoieXVzdWYyQG1haWwuY29tIiwiaWF0IjoxNzUzMDM1OTUxLCJleHAiOjE3NTMwNDMxNTF9.28qbdPKb7SkDSbKffXvrl_056RR6vzsGLdquFyAVwiM

------WebkitBoundary
Content-Disposition: form-data; name="email"

yusuf1@gmail.com
------WebkitBoundary
Content-Disposition: form-data; name="password"

1111
------WebkitBoundary
Content-Disposition: form-data; name="picture"; filename="ccc.png"
Content-Type: image/png

< ./ccc.png
------WebkitBoundary--

###
GET /users/transaction-history HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoieXVzdWZAbWFpbC5jb20iLCJpYXQiOjE3NTMwMzkyOTEsImV4cCI6MTc1MzA0NjQ5MX0.8E66M2JIUfyEYBjxs2cPR5IwuCKH0lcWbIw_wJMdQmc

###

GET /transaction/all-transaction HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJpYXQiOjE3NTMwNDE5OTksImV4cCI6MTc1MzA0OTE5OX0.4Pro3u2pMRkvGF62nxFJW76-u4ZgAabLceKxNbcWJ1c

###

GET /transaction/booked_seats?movie_id=12&movie_date=2025-07-16&cinema=2&time=1&location=2 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJpYXQiOjE3NTMwNDE5OTksImV4cCI6MTc1MzA0OTE5OX0.4Pro3u2pMRkvGF62nxFJW76-u4ZgAabLceKxNbcWJ1c

###

POST /transaction HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJpYXQiOjE3NTMwNDE5OTksImV4cCI6MTc1MzA0OTE5OX0.4Pro3u2pMRkvGF62nxFJW76-u4ZgAabLceKxNbcWJ1c


{
  "name": "Yusuf Bahtiar",
  "email": "yusuf@mail.com",
  "phone": "08123456789",
  "total_amount": 90000,
  "movie_date": "2025-07-16",
  "cinema_id": 2,
  "location_id": 2,
  "movie_id": 12,
  "payment_method_id": 1,
  "time_id": 1,
  "seats": ["A1", "A2"]
}





